version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"       # 호스트의 8080 포트를 컨테이너의 80 포트와 연결
    volumes:
      - ./src:/var/www/html   # 코드 변경 시 자동 반영
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # 초기 스크립트 실행을 원한다면 아래와 같이 마운트할 수 있음
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
