services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    build: ./mysql-conf
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_db
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # 초기 SQL 스크립트 실행 (필요 없으면 제거)
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


volumes:
  db_data:
